import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { auth } from "../auth";
import TransitionProvider from "./transition-provider";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"]
});

const GeistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${GeistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-50 py-4 bg-black/40 backdrop-blur animate-fade-in">
          <div className="w-full px-6">
            <div className="mx-auto max-w-[1200px] flex items-center justify-between h-16">
              {/* logo */}
              <Link href="/" className="text-xl font-bold text-white hover:opacity-90 transition-opacity">AI-Symptom</Link>
              {/* simple nav */}
              <nav className="flex items-center gap-6 text-sm font-medium">
                <Link href="/" className="text-white hover:opacity-90 transition-opacity">Home</Link>
                <Link href="/chatbot" className="text-white hover:opacity-90 transition-opacity">Chatbot</Link>
                <Link href="/contact" className="text-white hover:opacity-90 transition-opacity">Contact</Link>
                <Link
                  href="/login"
                  className="ml-4 inline-block rounded-full bg-accent-bright text-black px-4 py-1.5 text-sm font-semibold hover:bg-accent-bright/90 transition-colors"
                >
                  {session?.user ? (
                    <span>Account</span>
                  ) : (
                    <span>Login</span>
                  )}
                </Link>
              </nav>
            </div>
          </div>
        </header>
        <main className="min-h-[calc(100dvh-6rem)] w-full">
          <TransitionProvider>
            {children}
          </TransitionProvider>
        </main>
      </body>
    </html>
  );
}
