import { Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { auth } from "../auth";
import TransitionProvider from "./transition-provider";

const poppins = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"]
});

const GeistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${GeistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-50 animate-fade-in">
          {/* Outer wrapper with side padding to keep pill centered and not full width */}
          <div className="w-full px-4 md:px-6 mt-4">
            {/* Centered pill navbar */}
            <div className="mx-auto max-w-[1200px] h-16 glass rounded-full px-4 sm:px-6 flex items-center justify-between shadow-[0_0_24px_rgba(15,118,110,0.18)]">
            <Link href="/" className="flex items-center gap-3">
              {/* Image */}
              <span className="text-sm font-semibold tracking-wide text-[#0bbaac]">AI-Symptom</span>
            </Link>
            <nav className="flex items-center gap-6 text-base font-semibold">
              <Link href="/" className="text-[#0bbaac] hover:text-white hover:underline underline-offset-4 decoration-emerald-400/60 transition-colors hover-lift">Home</Link>
              <Link href="/chatbot" className="text-[#0bbaac] hover:text-white hover:underline underline-offset-4 decoration-emerald-400/60 transition-colors hover-lift">Chatbot</Link>
              <Link href="/contact" className="text-[#0bbaac] hover:text-white hover:underline underline-offset-4 decoration-emerald-400/60 transition-colors hover-lift">Contact</Link>
              
                <Link href="/login" className="text-[#0bbaac] hover:text-white transition-colors">{session?.user ? (
                <div className="flex items-center gap-3 max-w-[16rem]">
                  {session.user.image ? (
                   
                    <img
                      src={session.user.image}
                      alt={session.user.name ?? "User"}
                      className="h-8 w-8 rounded-full border border-white/20 object-cover"
                    />
                  ) : (
                    <span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-white/10 text-[#0bbaac]">
                      {(session.user.name?.[0] ?? "U").toUpperCase()}
                    </span>
                  )}
                  <span className="text-[#0bbaac] truncate">{session.user.name ?? session.user.email ?? "Account"}</span>
                </div>
              ) : "Login"}</Link>
              
            </nav>
            </div>
          </div>
        </header>
        <main className="min-h-[calc(100dvh-4rem)] w-full px-4 py-8">
          <TransitionProvider>
            {children}
          </TransitionProvider>
        </main>
      </body>
    </html>
  );
}
